"""
Wiki generator: creates graphify-out/wiki/index.md + one page per node.
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from .graph import Graph, NodeInfo


def generate_wiki(graph: Graph, out_dir: Path) -> None:
    wiki_dir = out_dir / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)

    # Group nodes by community for index
    community_groups: dict[int, List[str]] = {}
    for path, info in graph.nodes.items():
        community_groups.setdefault(info.community, []).append(path)

    # --- index.md ---
    index_lines: List[str] = [
        "# Wiki Index",
        "",
        "> Auto-generated by `graphify`. Use this file to navigate the knowledge graph.",
        "",
        "## Communities",
        "",
    ]

    for cid, members in sorted(community_groups.items(), key=lambda x: -len(x[1])):
        index_lines.append(f"### Community {cid} ({len(members)} nodes)")
        index_lines.append("")
        for m in sorted(members):
            info = graph.nodes[m]
            safe_name = _safe_filename(m)
            degree = graph.total_degree(m)
            index_lines.append(f"- [{m}](nodes/{safe_name}.md) `{info.kind}` ★{degree}")
        index_lines.append("")

    index_lines += [
        "---",
        "",
        "## All Nodes A–Z",
        "",
    ]
    for path in sorted(graph.nodes.keys()):
        info = graph.nodes[path]
        safe_name = _safe_filename(path)
        index_lines.append(f"- [{path}](nodes/{safe_name}.md) `{info.language}` `{info.kind}`")

    (wiki_dir / "index.md").write_text("\n".join(index_lines), encoding="utf-8")

    # --- one page per node ---
    nodes_dir = wiki_dir / "nodes"
    nodes_dir.mkdir(exist_ok=True)

    for path, info in graph.nodes.items():
        _write_node_page(nodes_dir, path, info, graph)


def _write_node_page(nodes_dir: Path, path: str, info: NodeInfo, graph: Graph) -> None:
    lines: List[str] = [
        f"# `{path}`",
        "",
        f"**Kind**: `{info.kind}` | **Language**: `{info.language}` | **Lines**: {info.line_count:,}",
        "",
    ]

    if info.description:
        lines += [f"> {info.description}", ""]

    if info.symbols:
        lines += [
            "## Exported Symbols",
            "",
            ", ".join(f"`{s}`" for s in info.symbols),
            "",
        ]

    deps = sorted(graph.dependencies(path))
    if deps:
        lines += ["## Dependencies (imports)", ""]
        for d in deps:
            lines.append(f"- [{d}]({_safe_filename(d)}.md)")
        lines.append("")

    dependents = sorted(graph.dependents(path))
    if dependents:
        lines += ["## Used By (dependents)", ""]
        for d in dependents:
            lines.append(f"- [{d}]({_safe_filename(d)}.md)")
        lines.append("")

    lines += [
        f"**Community**: {info.community}",
        f"**Degree**: {graph.total_degree(path)} (in={graph.in_degree(path)}, out={graph.out_degree(path)})",
        "",
        "---",
        "_Generated by graphify_",
    ]

    safe = _safe_filename(path)
    (nodes_dir / f"{safe}.md").write_text("\n".join(lines), encoding="utf-8")


def _safe_filename(path: str) -> str:
    """Convert a file path to a safe filename (no slashes)."""
    return path.replace("/", "__").replace("\\", "__").replace(".", "_")


def _pick_representative(members: List[str], graph: Graph) -> str:
    """Pick the most connected member as community representative."""
    return max(members, key=lambda m: graph.total_degree(m))
